// <auto-generated />
namespace Viddly3.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class MembershipType_IdCleanUp : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MembershipType_IdCleanUp));
        
        string IMigrationMetadata.Id
        {
            get { return "201910040200312_MembershipType_IdCleanUp"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
